using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CatcherGame.TextureManager
{
    /// <summary>
    /// 使用enum取key的string型態
    /// </summary>
    public enum TexturesKeyEnum
    {
        TEST = 0,

        MENU_BACKGROUND,
        MENU_SIDE,
        MENU_DICTIONARY_BUTTON,
        MENU_PLAY_BUTTON,
        MENU_HOW_TO_PLAY_BUTTON,
        MENU_TOP_SCORE_BUTTON,

        TOP_SCORE_DIALOG_BACK,
        TOP_SCORE_CLOSE_BUTTON,
        DIALOG_CLOSE_BUTTON,
        DIALOG_LEFT_BUTTON,
        DIALOG_RIGHT_BUTTON,

        GAME_START_COMIC_BACK,

        //PALY GAME----------------------------
        PLAY_BACKGROUND,
        PLAY_FLOOR,
        //FIREMAN
        PLAY_FIREMAN,
        PLAY_FIREMAN_LEFT,
        PLAY_FIREMAN_RIGHT,

        PLAY_LEFT_MOVE_BUTTON,
        PLAY_RIGHT_MOVE_BUTTON,
        PLAY_PAUSE_BUTTON,
        PLAY_SMOKE,
        PLAY_LIFE,
        PLAY_SCORE,
        //NET
        PLAY_NET_NORMAL,
        PLAY_NET_SMALL,
        PLAY_NET_LARGE,

        PLAY_DIE,
        PLAY_FLYOLDELADY_FALL,
        PLAY_FLYOLDELADY_CAUGHT,
        PLAY_FLYOLDELADY_WALK,

        PLAY_FATDANCE_FALL,
        PLAY_FATDANCE_CAUGHT,
        PLAY_FATDANCE_WALK,

        PLAY_LITTLEGIRL_FALL,
        PLAY_LITTLEGIRL_CAUGHT,
        PLAY_LITTLEGIRL_WALK,

        PLAY_MANSTUBBLE_FALL,
        PLAY_MANSTUBBLE_CAUGHT,
        PLAY_MANSTUBBLE_WALK,

        PLAY_NAUGHTYBOY_FALL,
        PLAY_NAUGHTYBOY_CAUGHT,
        PLAY_NAUGHTYBOY_WALK,

        PLAY_OLDMAN_FALL,
        PLAY_OLDMAN_CAUGHT,
        PLAY_OLDMAN_WALK,

        PLAY_ROXANNE_FALL,
        PLAY_ROXANNE_CAUGHT,
        PLAY_ROXANNE_WALK,

        PLAY_NICOLE_FALL,
        PLAY_NICOLE_CAUGHT,
        PLAY_NICOLE_WALK,

        PLAY_JASON_FALL,
        PLAY_JASON_CAUGHT,
        PLAY_JASON_WALK,

        //SMOKE
        PLAY_STRONG_SMOKE,
        //Item
        PLAY_ITEM_BOOSTING_SHOES,
        PLAY_ITEM_SLOW_SHOES,
        PLAY_ITEM_HEART,
        PLAY_ITEM_NET_SHRINKER,
        PLAY_ITEM_NET_EXPANDER,
        PLAY_ITEM_STRONG_SMOKE,
        //PAUSE DIALOG------------------------------
        PAUSE_DIALOG_BACK,
        PAUSE_EXIT,
        PAUSE_CONTINUE,

        //GAME OVER---------------------
        GAMEOVER_BACKGROUND,
        GAMEOVER_MENU_BUTTON,
        GAMEOVER_AGAIN_BUTTON,
        GAMEOVER_CHARACTER_SHOW_FOREGROUND,
        GAMEOVER_FACEBOOK_SHARE_BUTTON,

        //DICTIONARY---------------------
        DICTIONARY_BACKGROUND,
        DICTIONARY_CLOSE_BUTTON,
        DICTIONARY_LEFT_BUTTON,
        DICTIONARY_RIGHT_BUTTON,
        DICTIONARY_LITTLEGIRL_TEXTURE,
        DICTIONARY_LITTLEGIRL_INTRO_TEXTURE,
        DICTIONARY_FATDANCER_TEXTURE,
        DICTIONARY_FATDANCER_INTRO_TEXTURE,
        DICTIONARY_FLYOLDLADY_TEXTURE,
        DICTIONARY_FLYOLDLADY_INTRO_TEXTURE,
        DICTIONARY_MANSTUBBLE_TEXTURE,
        DICTIONARY_MANSTUBBLE_INTRO_TEXTURE,
        DICTIONARY_NAUGHTYBOY_TEXTURE,
        DICTIONARY_NAUGHTYBOY_INTRO_TEXTURE,
        DICTIONARY_OLDMAN_TEXTURE,
        DICTIONARY_OLDMAN_INTRO_TEXTURE,
        DICTIONARY_ROXANNE_TEXTURE,
        DICTIONARY_ROXANNE_INTRO_TEXTURE,
        DICTIONARY_NICOLE_TEXTURE,
        DICTIONARY_NICOLE_INTRO_TEXTURE,
        DICTIONARY_JASON_TEXTURE,
        DICTIONARY_JASON_INTRO_TEXTURE,
        DICTIONARY_NO,

        //HOWTOPLAY------------------------
        HOWTOPLAY_BACKGROUND,
        HOWTOPLAY_CLOSE_BUTTON,
        HOWTOPLAY_PAGE1,
        HOWTOPLAY_PAGE2
    }
}
